language: node_js
node_js:
    - "10"
    - "9"
    - "8"
install:
    - npm install --save-dev
script:
    - npm version
    - node index.js --from . --to . --max 10
    - node index.js --from . --to .
