language: node_js
node_js:
    - "10"
    - "9"
    - "8"
install:
    - npm install --save-dev
script:
    - npm version
    - node index.js --from node_modules --to . --max 5
    - node index.js --from node_modules --to .
sudo: true
